services:
  - type: web
    name: salesmaster
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        fromService:
          type: web
          name: salesmaster
          property: port

